version: "1.0.1"
services: 
  mongo_db: 
    container_name: mongo-dev
    image: mongo:latest
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_DATABASE=employee
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - ./mongodb_data:/data/db
  mongo-express:
    container_name: mongo-express
    image: mongo-express:latest
    depends_on:
      - mongo_db
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-dev
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
    ports:
      - 8081:8081
    restart: always
    volumes:
      - ./mongodb_data:/data/db
